## Tensorboard

tensorboard --logdir=""

In [1]:
import tensorflow as tf
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)

In [3]:
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./board/sample_1', sess.graph)
    print(sess.run(x))
    writer.close()

5


In [4]:
writer = tf.summary.FileWriter('./board/sample_2', tf.get_default_graph())
writer.close()

## Explicitly name operation node

In [ ]:
a = tf.constant(2, name='a')
b = tf.constant(3, name='b')
x = tf.add(a, b, name='add')

writer = tf.summary.FileWriter('./graph', tf.get_default_graph())
with tf.Session() as sess:
    print(sess.run(x))

## Constants

In [5]:
a = tf.constant([2,2], name='a')
b = tf.constant([[0,1],[2,3]], name='b')

In [6]:
print(a)

Tensor("a:0", shape=(2,), dtype=int32)


In [7]:
x = tf.multiply(a,b, name='mul')
with tf.Session() as sess:
    print(sess.run(x))

[[0 2]
 [4 6]]


## Filled with a specific value

- `tf.zeros(shape, dtype=tf.float32, name=None)`

In [8]:
a = tf.zeros([2,3], tf.int32)
with tf.Session() as sess:
    print(sess.run(a))

[[0 0 0]
 [0 0 0]]


- `tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True)`

In [9]:
a = tf.zeros_like([[1,2],[3,4],[5,6]])
with tf.Session() as sess:
    print(sess.run(a))

[[0 0]
 [0 0]
 [0 0]]


- `tf.ones(shape, dtype=tf.float32, name=None)`
- `tf.ones_like(input_tensor, dtype=None, name=None, optimize=True)`

- `tf.fill(dims, value, name=None)`

In [13]:
import numpy as np 

a = tf.fill([2,3], 8)
x = tf.constant(np.arange(20), shape=(2,10))
y = tf.tile(x, [1,2])
with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(x))
    print(sess.run(y))

[[8 8 8]
 [8 8 8]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 0  1  2  3  4  5  6  7  8  9  0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19 10 11 12 13 14 15 16 17 18 19]]


## Constants as sequences

- `tf.lin_space(start, stop, num, name=None)`

In [15]:
a = tf.lin_space(10.0, 13.0, 4)
with tf.Session() as sess:
    print(sess.run(a))

[ 10.  11.  12.  13.]


- `tf.range(start, limit=None, delta=1, dtype=None, name='range')`

Numpy sequece와는 다르다.
Tensor object는 iterable하지 않다

In [16]:
a = tf.range(3, 18, 3)
with tf.Session() as sess:
    print(sess.run(a))

[ 3  6  9 12 15]


## Randomly Generated Constants

## TF DataType

Tensorflow integrates seamlessly with Numpy

In [1]:
import tensorflow as tf
import numpy as np

tf.int32 == np.int32

True

Can pass numpy types to Tensorflow ops

In [2]:
tf.ones([2,2], dtype=np.float32)

<tf.Tensor 'ones:0' shape=(2, 2) dtype=float32>

In [4]:
sess = tf.Session()
a = tf.zeros([2,3], np.int32)
print(type(a))
a_out = sess.run(a)
print(type(a))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


## Constants

In [5]:
my_const = tf.constant([1.0, 2.0], name="my_const")
with tf.Session() as sess:
    print(sess.graph.as_graph_def())

node {
  name: "ones"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 2
          }
          dim {
            size: 2
          }
        }
        float_val: 1.0
      }
    }
  }
}
node {
  name: "zeros"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
          dim {
            size: 3
          }
        }
        int_val: 0
      }
    }
  }
}
node {
  name: "zeros_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
          dim {
            size: 3
   

## Variables

tf.constant is an op

tf.Variable is a class with many ops

In [ ]:
# create variables with tf.Variable

s = tf.Variable(2, name="scalar")
m = tf.Variable([[0,1],[2,3]], name='matrix')
W = tf.Variable(tf.zeros([784,10]))

# create variables with tf.get_variable
s = tf.get_variable("scalar", initializer=tf.constant(2))
m = tf.get_variable("matrix", initializer=tf.constant([[0,1],[2,3]]))
W = tf.get_variable("big_matrix", shape=(784,10), initializer=tf.zeros_initializer())

In [1]:
import tensorflow as tf

x = tf.Variable(2, name='scalar')

In [3]:
#x.initializer
x.value

<bound method Variable.value of <tf.Variable 'scalar:0' shape=() dtype=int32_ref>>

In [ ]:
x.assign()

TF allows you to omit the '.value' in many cases. so you can pass values of vars to other ops as tf.add(x,..) rather thann tf.add(x.value, ..)

In [4]:
W = tf.get_variable("big_matrix", shape=(784,10), initializer=tf.zeros_initializer())
with tf.Session() as sess:
    print(sess.run(W))
    # Attempting to use uninitialized value big_matrix

FailedPreconditionError: Attempting to use uninitialized value big_matrix
	 [[Node: big_matrix/_0 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_4_big_matrix", _device="/job:localhost/replica:0/task:0/gpu:0"](big_matrix)]]

## You have to initialize your variables

### 1.global_varialbes_initializer

In [3]:
import tensorflow as tf


W = tf.get_variable('big_matrix', shape=(784,10), initializer=tf.zeros_initializer())
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(W))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### 2.variables_initalizer

In [6]:
tf.reset_default_graph()
W = tf.get_variable('big_matrix', initializer=tf.zeros([784,10]))
# W = tf.get_variable('big_matrix', shape=(784,10), initializer=tf.zeros_initializer())
s = tf.get_variable('scalar', initializer=tf.constant(2))

with tf.Session() as sess:
    sess.run(tf.variables_initializer([W,s]))
    print(sess.run(W))
    print(sess.run(s))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
2


### 3.single variable initialzer + eval()

In [8]:
tf.reset_default_graph()

W = tf.Variable(tf.zeros([784, 10]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W)

<tf.Variable 'Variable:0' shape=(784, 10) dtype=float32_ref>


In [9]:
tf.reset_default_graph()

W = tf.Variable(tf.truncated_normal([700, 10]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())

[[ 0.5387366  -0.09136364 -0.4484122  ...  0.64024144 -0.90016574
  -0.17995478]
 [ 0.92640895 -1.1868834  -1.8441484  ...  0.17536591  0.89835227
   0.2853877 ]
 [-0.97877413  0.0060702  -0.8297479  ... -0.10628606 -0.9189984
   0.02864648]
 ...
 [ 0.6935989  -0.34958765  1.1187634  ...  0.9871344  -1.0166482
  -1.4708796 ]
 [-1.1970402  -1.1087104  -1.4080327  ... -0.72598743 -0.23861702
   0.23417957]
 [-0.8563113   0.906676   -1.2289336  ... -0.22043319  0.7046179
   1.2028685 ]]


## tf.Variable.assign()

variable.assing() creates an assign op. That op needs to be executed in a session to take effect.

You dont need to intialize variable because assign_op does it for you. 

In fact, initializer op is the assign op that assigns the variable's inital value to the variable itself.

In [11]:
tf.reset_default_graph()

W = tf.Variable(10)
W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())

10


In [13]:
tf.reset_default_graph()

W = tf.Variable(10)
assign_op = W.assign(100)
with tf.Session() as sess:
    # sess.run(W.initializer)
    sess.run(assign_op)
    print(W.eval())

100


In [15]:
tf.reset_default_graph()

my_var = tf.Variable(2, name='my_var')

my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    sess.run(my_var_times_two)
    print(sess.run(my_var))

4


In [16]:
tf.reset_default_graph()

my_var = tf.Variable(2, name='my_var')

my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    sess.run(my_var_times_two)
    sess.run(my_var_times_two)
    print(sess.run(my_var))

8


In [18]:
tf.reset_default_graph()

my_var = tf.Variable(2, name='my_var')

my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    sess.run(my_var_times_two)
    sess.run(my_var_times_two)
    sess.run(my_var_times_two)
    print(sess.run(my_var))

16


## tf.variable.assing_add() and assign_sub()

In [20]:
tf.reset_default_graph()

my_var = tf.Variable(10)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    sess.run(my_var.assign_add(10))
    print(sess.run(my_var))
    
    sess.run(my_var.assign_sub(2))
    print(sess.run(my_var))

20
18


## Each session maintains its own copy of variables

In [21]:
tf.reset_default_graph()
W = tf.Variable(10)

sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print(sess1.run(W.assign_add(10)))
print(sess2.run(W.assign_sub(2)))

20
8


In [22]:
print(sess1.run(W.assign_add(100)))
print(sess2.run(W.assign_sub(50)))

sess1.close()
sess2.close()

120
-42


## Control Dependencies

Sometimes, we will have two more independent ops but you would like to specify which op should be run first, then you use tf.Graph.control_depencies(control_inputs)

In [ ]:
tf.reset_default_graph()
a = tf.Variable(10)
b = tf.Variable(20)

sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print(sess1.run(W.assign_add(10)))
print(sess2.run(W.assign_sub(2)))

## Placeholders

A TF program often has 2 phases:

- `1. Assemble a graph`

- `2. Use a session to execute opertations in the graph`

-> Assemble the graph first without knowing the values needed for computation

without knwoing value of x or y.

x,y are placeholders for the actual values.

We can later supply their own data when they need to execute the computation.

**tf.placeholder(dtype, shape=None, name=None)**

**Placeholders are valid ops**

In [23]:
tf.reset_default_graph()
# create a placeholder for a vector of 3 elements, type tf.float32
a = tf.placeholder(tf.float32, shape=[3])

b = tf.constant([5,5,5], tf.float32)
print(b)
# use the placeholder as you would a constant or a variable
c = a+b

with tf.Session() as sess:
    print(sess.run(c))
# InvalidArgumentError: 
# You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [3]

Tensor("Const:0", shape=(3,), dtype=float32)


InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [3]
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[3], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
	 [[Node: add/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_7_add", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Placeholder', defined at:
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\tornado\platform\asyncio.py", line 112, in start
    self.asyncio_loop.run_forever()
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\asyncio\base_events.py", line 1425, in _run_once
    handle._run()
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\tornado\platform\asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\IPython\core\interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-1cff078061da>", line 3, in <module>
    a = tf.placeholder(tf.float32, shape=[3])
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1777, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 5496, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\tensorflow\python\framework\ops.py", line 3290, in create_op
    op_def=op_def)
  File "D:\Program Files\Anaconda3\envs\tensorflow_1_7\lib\site-packages\tensorflow\python\framework\ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [3]
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[3], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
	 [[Node: add/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_7_add", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


In [30]:
tf.reset_default_graph()
# create a placeholder for a vector of 3 elements, type tf.float32
a = tf.placeholder(tf.float32, shape=None) #shape=[3]
print(a)
b = tf.constant([5,5,5], tf.float32)
print(b)
# use the placeholder as you would a constant or a variable
c = a+b
print(c)
d = tf.Variable([5,5,5])
print(d)
with tf.Session() as sess:
    print(sess.run(c, feed_dict={a : [1,2,3]}))

Tensor("Placeholder:0", dtype=float32)
Tensor("Const:0", shape=(3,), dtype=float32)
Tensor("add:0", dtype=float32)
<tf.Variable 'Variable:0' shape=(3,) dtype=int32_ref>
[6. 7. 8.]


shape=None menas that tensor of any shape will be accepted as value for placeholder.

shape=None is easy to construct graphs, but niightmarish for debugging

shape=None also breaks all following shape inference, which makes many ops not work because they expect certain rank.

In [31]:
tf.reset_default_graph()
# create a placeholder for a vector of 3 elements, type tf.float32
a = tf.placeholder(tf.float32, shape=None) #shape=[3]

b = tf.constant([5,5,5], tf.float32)

# use the placeholder as you would a constant or a variable
c = a+b

list_of_values_for_a = [1,2,3,4,5,6]
with tf.Session() as sess:
    for a_value in list_of_values_for_a:
        print(sess.run(c, {a: a_value}))
        
    

[6. 6. 6.]
[7. 7. 7.]
[8. 8. 8.]
[9. 9. 9.]
[10. 10. 10.]
[11. 11. 11.]


b

In [34]:
b = tf.constant([5,5,5], tf.float32)
list_of_values_for_a = [1,2,3,4,5,6]
tf.Graph.is_feedable(b)

TypeError: is_feedable() missing 1 required positional argument: 'tensor'

## Feeding values to TF ops

In [36]:
a = tf.add(2,5)
b = tf.multiply(a,3)

with tf.Session() as sess:
    print(sess.run(b, feed_dict={a:15}))

45


## Lazy loading

defer creating/initializing an object until it is needed

In [1]:
import tensorflow as tf

In [2]:
# Normal Loading
tf.reset_default_graph()
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x,y)


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter('./graphs/normal_loading', tf.get_default_graph())
    for _ in range(20):
        sess.run(z)
    print(tf.get_default_graph().as_graph_def())
    writer.close()

node {
  name: "x/initial_value"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 10
      }
    }
  }
}
node {
  name: "x"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "x/Assign"
  op: "Assign"
  input: "x"
  input: "x/initial_value"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@x"
      }
    }
  }
  attr {
    key: "use_locking"
    value {
      b: true
    }
  }
  attr {
    key: "validate_shape"
    value {
      b: true
    }
  }
}
node {
  name: "x/read"
  op: "Identity"
  input

In [3]:
# Lazy Loading
tf.reset_default_graph()
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter('./graphs/normal_loading', tf.get_default_graph())
    for _ in range(20):
        sess.run(tf.add(x,y))
    print(tf.get_default_graph().as_graph_def())
    writer.close()

node {
  name: "x/initial_value"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 10
      }
    }
  }
}
node {
  name: "x"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "x/Assign"
  op: "Assign"
  input: "x"
  input: "x/initial_value"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@x"
      }
    }
  }
  attr {
    key: "use_locking"
    value {
      b: true
    }
  }
  attr {
    key: "validate_shape"
    value {
      b: true
    }
  }
}
node {
  name: "x/read"
  op: "Identity"
  input

## Solution

1. Seperate definition of ops from computing/running ops

2. Use Python Property to ensure function is also loaded once the first time it is called